# Generated by Django 6.0.5 on 2026-05-06 17:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('feed_type', models.CharField(choices=[('rss', 'RSS'), ('atom', 'Atom'), ('web', 'Web')], default='rss', max_length=10)),
                ('content_selector', models.CharField(blank=True, default='', max_length=500)),
                ('strip_selectors', models.TextField(blank=True, default='')),
                ('crawl_interval', models.IntegerField(default=60, help_text='Crawl interval in minutes')),
                ('auto_rewrite', models.BooleanField(default=False)),
                ('editorial_review', models.BooleanField(default=False)),
                ('region', models.CharField(choices=[('ugandan', 'Ugandan'), ('east_african', 'East African'), ('international', 'International')], default='international', max_length=20)),
                ('download_images', models.BooleanField(default=True)),
                ('nofollow', models.BooleanField(default=True)),
                ('attribution_text', models.CharField(blank=True, default='', max_length=500)),
                ('max_articles', models.IntegerField(default=50)),
                ('avg_articles_per_day', models.FloatField(default=0.0)),
                ('consecutive_empty', models.IntegerField(default=0)),
                ('consecutive_failures', models.IntegerField(default=0)),
                ('last_crawled_at', models.DateTimeField(blank=True, null=True)),
                ('last_new_content_at', models.DateTimeField(blank=True, null=True)),
                ('next_crawl_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawl_sources', to='articles.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CrawlLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('error', 'Error')], default='ok', max_length=10)),
                ('found_count', models.IntegerField(default=0)),
                ('new_count', models.IntegerField(default=0)),
                ('duplicate_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('duration_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='crawler.crawlsource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
