# Generated by Django 6.0.5 on 2026-05-06 17:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('value', models.TextField(blank=True, default='')),
                ('type', models.CharField(choices=[('string', 'String'), ('bool', 'Boolean'), ('int', 'Integer'), ('json', 'JSON')], default='string', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
                'db_table': 'site_settings',
                'ordering': ['key'],
            },
        ),
    ]
