# Generated by Django 6.0.5 on 2026-05-06 17:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slot_name', models.CharField(max_length=100, unique=True)),
                ('html_content', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('device_targeting', models.CharField(choices=[('all', 'All Devices'), ('mobile', 'Mobile'), ('desktop', 'Desktop')], default='all', max_length=10)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('banner', 'Banner'), ('modal', 'Modal'), ('sidebar', 'Sidebar'), ('slide_in', 'Slide In'), ('full_screen', 'Full Screen')], default='modal', max_length=20)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('device_targeting', models.CharField(choices=[('all', 'All Devices'), ('mobile', 'Mobile'), ('desktop', 'Desktop')], default='all', max_length=10)),
                ('trigger_type', models.CharField(blank=True, default='', max_length=50)),
                ('trigger_value', models.CharField(blank=True, default='', max_length=100)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('variant', models.CharField(blank=True, help_text='A/B test variant identifier', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
