# Generated by Django 5.1.15 on 2026-07-11 07:45

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django.indexes
from django.conf import settings
from django.contrib.postgres.operations import (
    AddIndexConcurrently,
    TrigramExtension,
)
from django.db import migrations, models


class Migration(migrations.Migration):
    # Non-atomic so the GIN/HNSW indexes can be built CONCURRENTLY (Postgres
    # forbids CREATE INDEX CONCURRENTLY inside a transaction) — that keeps the
    # *index builds* off the ACCESS EXCLUSIVE lock a plain AddIndex would take.
    #
    # CAVEAT: the AddField below adds a STORED GeneratedField (db_persist=True),
    # which rewrites the whole table under ACCESS EXCLUSIVE for its duration
    # REGARDLESS of atomic=False. That is instant on a small/empty table but is a
    # write-blocking window on a large populated one. If this table ever grows
    # large, split that column-add into a controlled step (add nullable +
    # backfill in batches, or run during a maintenance window) rather than
    # relying on this migration.
    atomic = False

    dependencies = [
        ('articles', '0002_article_metrics_and_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # pg_trgm powers the ``%`` operator used by the trigram GIN index below.
        TrigramExtension(),
        migrations.AddField(
            model_name='article',
            name='search_vector',
            field=models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.SearchVector('title', config='english', weight='A'), '||', django.contrib.postgres.search.SearchVector('excerpt', config='english', weight='B'), django.contrib.postgres.search.SearchConfig('english')), '||', django.contrib.postgres.search.SearchVector('ai_summary', config='english', weight='B'), django.contrib.postgres.search.SearchConfig('english')), '||', django.contrib.postgres.search.SearchVector('content', config='english', weight='C'), django.contrib.postgres.search.SearchConfig('english')), output_field=django.contrib.postgres.search.SearchVectorField()),
        ),
        migrations.AlterField(
            model_name='articlerevision',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_revisions', to=settings.AUTH_USER_MODEL),
        ),
        AddIndexConcurrently(
            model_name='article',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='article_fts_gin'),
        ),
        AddIndexConcurrently(
            model_name='article',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(models.F('title'), name='gin_trgm_ops'), name='article_title_trgm'),
        ),
        AddIndexConcurrently(
            model_name='article',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='article_emb_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
