# Generated by Django 5.1.15 on 2026-07-12 10:45

import secrets

from django.db import migrations, models


def backfill_tokens(apps, schema_editor):
    """Give every existing follow a unique unfollow token (empty tokens would
    collide in the tokenized unfollow lookup)."""
    TopicFollow = apps.get_model('articles', 'TopicFollow')
    for f in TopicFollow.objects.filter(unfollow_token=''):
        f.unfollow_token = secrets.token_urlsafe(32)
        f.save(update_fields=['unfollow_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_rename_northern_uganda_to_local_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicfollow',
            name='unfollow_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.RunPython(backfill_tokens, migrations.RunPython.noop),
    ]
