# Generated by Django 5.1.15 on 2026-07-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_topicfollow_unfollow_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='geo_place',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='article',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
